package com.softarum.svsa.modelo.enums.ct;
/*
 * @author laurojr
 *
 */

public enum DireitoViolado {
	
	VIDA,
	SAUDE,
	ALIMENTACAO,
	EDUCACAO,
	ESPORTES,
	LAZER,
	PROFISSIONALIZACAO,
	CULTURA,
	LIBERDADE,
	RESPEITO,
	DIGNIDADE,
	CONVIVENCIA_FAMILIAR_COMUNITARIA,
	NEGLIGENCIA_SAUDE_HIGIENE,
	NEGLIGENCIA_ALIMENTACAO,
	MAUS_TRATOS_FISICOS,
	MAUS_TRATOS_VERBAL_PSICOLOGICO,
	ABANDONO_DE_INCAPAZ,
	SUSPEITA_VVS,
	EXPLORACAO_SEXUAL_INFANTIL,
	TRABALHO_INFANTIL,
	CONFLITO_FAMILIAR,
	CONVIVENCIA_FAMILIAR,
	SUSPEITA_USO_DROGAS_ADOLESCENTE,
	INDICISPLICA_ESCOLAR,
	EVASAO_ESCOLAR,
	FALTA_ESCOLAR,
	AGRESSAO_FISICA_ESCOLA,
	BULLYING,
	DIFICULDADE_DE_APRENDIZAGEM
}
